### ISSUE TITLE
Ошибка установки на русскоязычной версии ubuntu

### ISSUE THREAD

**Issue by dinamicby** [igroman787/mytonctrl#1]
При установке на ubuntu с русским языком, на этапе вызова toninstaller.sh, появляется ошибка:
```
Collecting psutil
  Using cached https://files.pythonhosted.org/packages/c4/b8/3512f0e93e0db23a71d82485ba256071ebef99b227351f0f5540f744af41/psutil-5.7.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ModuleNotFoundError: No module named 'setuptools'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-rmblts3l/psutil/
```

Решилось путём выполнения 
sudo pip3 install --upgrade pip setuptools wheel (скорее всего не обязательно)
sudo pip3 install python-language-server

Предлагаю добавить в установочный скрипт эти строчки

**Comment by igroman787** [comment]
Протестируем и исправим. Спасибо

**Comment by igroman787** [comment]
Данная проблема была исправлена данным коммитом: https://github.com/igroman787/mytonctrl/commit/2050b9e81bf0b79e0392b92b694f83250937b997
