### ISSUE TITLE
Flag Association Change in Commit ce83ac7c, file mytoninstaller.py, function General, line 204.

### ISSUE THREAD

**Issue by ice-hermes** [igroman787/mytonctrl#153]
In the commit ce83ac7c111ff2c320954e528cf0ff8e79c177f9, there appears to be a significant change. I'm not completely certain about the specifics of the code changes, but it looks like before this commit, the following logic:

		# Создать настройки для mytoncore.py
		FirstMytoncoreSettings()

		if mode == "full":
			FirstNodeSettings()
			EnableValidatorConsole()
			EnableLiteServer()
			BackupVconfig()
			BackupMconfig()
		#end if

		# Создать символические ссылки
		CreateSymlinks()

was associated with the "-m" (mode) flag. However, post-commit, it seems to be linked with the "--dump" flag. @igroman787, could you please review this and confirm if this modification was intentional?

**Comment by igroman787** [comment]
You're right
This error was fixed in the `mytonctrl2` branch:
https://github.com/ton-blockchain/mytonctrl/commit/0d64eef9c0fa9a0a74103ab620137c9faf4759f4

And soon `mytonctrl2` branch will be merge into the `master` branch
