### ISSUE TITLE
Is local validator wallet address correct?

### ISSUE THREAD

**Issue by kesha-antonov** [igroman787/mytonctrl#36]
Hi!

We've started `mon` process but we have

```Local validator wallet address: kf8gGTuya0marR3tNRjipI_Mryik_6X683RgJOPxOK6d8yGS```
Is it correct?

Even though we have set our wallet like this:
```
moff
set powAddr “auto”
set minerAddr “EQDCulTFDHn4O6tLYzssDmKtpr7bSt2G2nHuPogmcI2VgfYe”
mon
```

![photo_2021-08-06 09 02 40](https://user-images.githubusercontent.com/11584712/128463640-87ab2f54-c2ac-4911-abf5-b0bf5d2ae949.jpeg)

**Comment by igroman787** [comment]
The mining and validation process are different processes.
Accordingly, the screenshot displays the validator's wallet - from where the coins will be frozen in favor of the bet. And then you will be the validator.

For mining, you don't need to be a validator. It is enough to start the mining process - solving tasks that are given by PoW-givers. And also indicate where the mining reward will be sent.

You did everything right. To view the wallet that will receive the mining reward, you can use the `get minerAddr` command.

**Comment by kesha-antonov** [comment]
> The mining and validation process are different processes.
> Accordingly, the screenshot displays the validator's wallet - from where the coins will be frozen in favor of the bet. And then you will be the validator.
> 
> For mining, you don't need to be a validator. It is enough to start the mining process - solving tasks that are given by PoW-givers. And also indicate where the mining reward will be sent.
> 
> You did everything right. To view the wallet that will receive the mining reward, you can use the `get minerAddr` command.

Thanks!
