### ISSUE TITLE
how to uninstall mytonctrl

### ISSUE THREAD

**Issue by ruban-s** [igroman787/mytonctrl#52]
hi, installed mytonctrl in ubuntu 20.4 after that i moved to another high conf cpu system now i need unistall/delete mytonctrl from old system

**Comment by dharnarh** [comment]
How to remove mytonctrl:
run the script as administrator and remove the compiled TON components:
`sudo bash /usr/src/mytonctrl/scripts/uninstall.sh`
`sudo rm -rf /usr/bin/ton`
