### ISSUE TITLE
Troubles with toninstaller

### ISSUE THREAD

**Issue by com-master** [igroman787/mytonctrl#8]
toninstaller.sh: 17: toninstaller.sh: [[: not found
toninstaller.sh: 23: toninstaller.sh: [[: not found
toninstaller.sh: 51: toninstaller.sh: [[: not found
toninstaller.sh: 64: toninstaller.sh: [[: not found
Ну чо такое((

**Comment by com-master** [comment]
Traceback (most recent call last):
  File "mytonctrl.py", line 4, in <module>
    from mypylib.mypylib import *
ModuleNotFoundError: No module named 'mypylib.mypylib'

Хотя есть папка mypylib

**Comment by igroman787** [comment]
Данная проблема была исправлена данным коммитом: https://github.com/igroman787/mytonctrl/commit/2050b9e81bf0b79e0392b92b694f83250937b997
