### ISSUE TITLE
dbLoad: [Errno 2] No such file or directory: '/usr/local/bin/mytoncore/mytoncore.db'

### ISSUE THREAD

**Issue by com-master** [igroman787/mytonctrl#9]
dbLoad: [Errno 2] No such file or directory: '/usr/local/bin/mytoncore/mytoncore.db'

**Comment by igroman787** [comment]
Данная проблема была исправлена данным коммитом: https://github.com/igroman787/mytonctrl/commit/2050b9e81bf0b79e0392b92b694f83250937b997
